# Generated by Django 3.1.2 on 2020-10-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0003_auto_20201025_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')]),
        ),
    ]
